### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by themars** [qjpcpu/qjpcpu.github.com#1]
I couldn't find the way to contact you, so I decided to make an issue on one of you projects. I need your advice on websocket-rails gem that you forked. I'm trying to use it in my own project and got errors:

```
I [8589] [2016-01-08 04:38:03.204] [EventProcessor] Started Event: users.list
I [8589] [2016-01-08 04:38:03.204] [EventProcessor] Name: users.list
I [8589] [2016-01-08 04:38:03.204] [EventProcessor] Data: {}
I [8589] [2016-01-08 04:38:03.204] [EventProcessor] Connection: #<Connection::c8613959-52d1-45d0-990c-80ae8790da23>
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] NoMethodError: undefined method `authenticate!' for nil:NilClass
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/devise-3.5.3/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/base_controller.rb:190:in `method_missing'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:429:in `block in make_lambda'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:161:in `call'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:161:in `block in halting'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:501:in `call'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:501:in `block in call'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:501:in `each'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:501:in `call'
E [8589] [2016-01-08 04:38:03.207] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:86:in `run_callbacks'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/gems/actionpack-4.1.13/lib/abstract_controller/callbacks.rb:19:in `process_action'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/message_processors/event_processor.rb:36:in `block (2 levels) in route'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/logging.rb:67:in `log_event'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/message_processors/event_processor.rb:33:in `block in route'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:125:in `call'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:125:in `block in routes_for'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:124:in `each'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:124:in `routes_for'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:130:in `routes_for'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_map.rb:40:in `routes_for'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/message_processors/event_processor.rb:31:in `route'
E [8589] [2016-01-08 04:38:03.208] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/message_processors/event_processor.rb:24:in `process_message'

E [8589] [2016-01-08 04:38:03.209] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/dispatcher.rb:34:in `block (2 levels) in process_inbound'
E [8589] [2016-01-08 04:38:03.209] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/dispatcher.rb:33:in `each'
E [8589] [2016-01-08 04:38:03.209] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/dispatcher.rb:33:in `block in process_inbound'
E [8589] [2016-01-08 04:38:03.209] [EventProcessor] /home/mars/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-2df65dfe1ef5/lib/websocket_rails/event_queue.rb:28:in `block (2 levels) in pop'
```

What is the best way to contact you? Thank you!

**Comment by qjpcpu** [comment]
Hi, themas,
The `WebsocketRails::BaseController` would delegate any method which not found in it, so I think there's a `authenticate_user!` before filter in your websocket controller, and a signed user can't be found in it. Check your authorization filters configuration, and let me know if you solve the problem. ^_^
and my mail: qjpcpu@gmail.com.
